services:
  nginx:
    image: nginx:alpine
    container_name: solux-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/ssl:/etc/nginx/ssl:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
